
# AUTOMATICALLY GENERATED BY THE PDL TOPLEVEL Makefile.PL.
# DO NOT HAND-EDIT - CHANGES WILL BE LOST UPON YOUR NEXT
#  'perl Makefile.PL'!!!
package PDL;
%PDL::Config = (
	BADVAL_PER_PDL	=>	"0",
	WITH_PROJ	=>	undef,
	FFTW_TYPE	=>	"double",
	FFTW_LIBS	=>	["\/lib","\/usr\/lib64","\/usr\/lib","\/usr\/local\/lib"],
	WITH_FFTW	=>	undef,
	GSL_LIBS	=>	undef,
	GL_BUILD	=>	"1",
	WITH_IO_BROWSER	=>	"1",
	PROJ_INC	=>	undef,
	WHERE_PLPLOT_INCLUDE	=>	undef,
	WITH_KARMA	=>	"0",
	WHERE_KARMA	=>	undef,
	HTML_DOCS	=>	"1",
	WHERE_PLPLOT_LIBS	=>	undef,
	WITH_3D	=>	"1",
	FFTW_INC	=>	["\/usr\/include\/","\/usr\/local\/include"],
	WITH_POSIX_THREADS	=>	"1",
	HIDE_TRYLINK	=>	"1",
	WITH_HDF	=>	undef,
	HDF_INC	=>	undef,
	OPENGL_LIBS	=>	"\-L\/usr\/lib64\/\ \-lGLU\ \-lGL\ \-lX11\ \-lm",
	WITH_BADVAL	=>	"0",
	WITH_GD	=>	undef,
	FITS_LEGACY	=>	"1",
	WITH_SLATEC	=>	"1",
	BADVAL_USENAN	=>	"0",
	TEMPDIR	=>	"\/tmp",
	PROJ_LIBS	=>	undef,
	GD_LIBS	=>	undef,
	GSL_INC	=>	undef,
	GD_INC	=>	undef,
	OPTIMIZE	=>	undef,
	WITH_GSL	=>	undef,
	HDF_LIBS	=>	undef,
	MALLOCDBG	=>	{},
	WITH_PLPLOT	=>	"1",
);
1;