
# AUTOMATICALLY GENERATED BY THE PDL TOPLEVEL Makefile.PL.
# DO NOT HAND-EDIT - CHANGES WILL BE LOST UPON YOUR NEXT
#  'perl Makefile.PL'!!!
package PDL;
use File::Spec;
%PDL::Config = (
	BADVAL_PER_PDL	=>	"0",
	WITH_PROJ	=>	undef,
	FFTW_TYPE	=>	"double",
	FFTW_LIBS	=>	["\/lib","\/usr\/lib","\/usr\/local\/lib"],
	WITH_FFTW	=>	undef,
	GSL_LIBS	=>	undef,
	GL_BUILD	=>	"0",
	WITH_IO_BROWSER	=>	"0",
	PROJ_INC	=>	undef,
	WHERE_PLPLOT_INCLUDE	=>	undef,
	WITH_KARMA	=>	"0",
	WHERE_KARMA	=>	undef,
	HTML_DOCS	=>	"1",
	WHERE_PLPLOT_LIBS	=>	undef,
	WITH_3D	=>	undef,
	POGL_VERSION	=>	"0\.6",
	FFTW_INC	=>	["\/usr\/include\/","\/usr\/local\/include"],
	WITH_POSIX_THREADS	=>	"1",
	HIDE_TRYLINK	=>	"1",
	WITH_HDF	=>	undef,
	HDF_INC	=>	undef,
	POGL_WINDOW_TYPE	=>	"glut",
	WITH_BADVAL	=>	"1",
	WITH_GD	=>	undef,
	FITS_LEGACY	=>	"1",
	WITH_SLATEC	=>	undef,
	BADVAL_USENAN	=>	"0",
	TEMPDIR	=>	"\/tmp",
	PROJ_LIBS	=>	undef,
	USE_POGL	=>	"1",
	GD_LIBS	=>	undef,
	GSL_INC	=>	undef,
	GD_INC	=>	undef,
	WITH_GSL	=>	undef,
	OPTIMIZE	=>	undef,
	HDF_LIBS	=>	undef,
	MALLOCDBG	=>	{},
	WITH_MINUIT	=>	undef,
	WITH_PLPLOT	=>	"0",
	MINUIT_LIB	=>	undef,
);
1;