###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.04).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file bo.xml.
# The source file version number was 1.6, generated on
# 2007/07/19 22:31:38.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::bo;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::bo::ISA = qw(DateTime::Locale::root);

my @day_names = (
"གཟའ་ཟླ་བ་",
"གཟའ་མིག་དམར་",
"གཟའ་ཧླག་པ་",
"གཟའ་ཕུར་བུ་",
"གཟའ་སངས་",
"གཟའ་སྤེན་པ་",
"གཟའ་ཉི་མ་",
);

my @day_abbreviations = (
"ཟླ་བ་",
"མིག་དམར་",
"ཧླག་པ་",
"ཕུར་བུ་",
"སངས་",
"སྤེན་པ་",
"ཉི་མ་",
);

my @day_narrows = (
"ཟླ",
"མི",
"ཧླ",
"ཕུ",
"ས",
"སྤེ",
"ཉི",
);

my @month_names = (
"ཟླ་བ་དང་པོ་",
"ཟླ་བ་གཉིས་པ་",
"ཟླ་བ་སུམ་པ་",
"ཟླ་བ་བཞི་པ་",
"ཟླ་བ་ལྔ་པ་",
"ཟླ་བ་དྲུག་པ་",
"ཟླ་བ་བདུན་པ་",
"ཟླ་བ་བརྒྱད་པ་",
"ཟླ་བ་དགུ་པ་",
"ཟླ་བ་བཅུ་པ་",
"ཟླ་བ་བཅུ་གཅིག་པ་",
"ཟླ་བ་བཅུ་གཉིས་པ་",
);

my @month_abbreviations = (
"ཟླ་༡",
"ཟླ་༢",
"ཟླ་༣",
"ཟླ་༤",
"ཟླ་༥",
"ཟླ་༦",
"ཟླ་༧",
"ཟླ་༨",
"ཟླ་༩",
"ཟླ་༡༠",
"ཟླ་༡༡",
"ཟླ་༡༢",
);

my @quarter_names = (
"དུས་ཚིགས་དང་པོ།",
"དུས་ཚིགས་གཉིས་པ།",
"་དུས་ཚིགས་གསུམ་པ།",
"དུས་ཚིགས་བཞི་པ།",
);

my @quarter_abbreviations = (
"དུས་ཚིགས་དང་པོ།",
"དུས་ཚིགས་གཉིས་པ།",
"་དུས་ཚིགས་གསུམ་པ།",
"དུས་ཚིགས་བཞི་པ།",
);

my @am_pms = (
"སྔ་དྲོ་",
"ཕྱི་དྲོ་",
);

my @era_names = (
"སྤྱི་ལོ་སྔོན།",
"སྤྱི་ལོ།",
);

my @era_abbreviations = (
"སྤྱི་ལོ་སྔོན།",
"སྤྱི་ལོ།",
);



sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub day_narrows                    { \@day_narrows }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub quarter_names                  { \@quarter_names }
sub quarter_abbreviations          { \@quarter_abbreviations }
sub am_pms                         { \@am_pms }
sub era_names                      { \@era_names }
sub era_abbreviations              { \@era_abbreviations }
sub long_date_format               { "སྦྱི་ལོ་\%\{ce_year\}\ \%Bའི་ཙེས་\%\{day\}ད" }
sub medium_date_format             { "\%\{ce_year\}\ ལོ་འི་\%bཙེས་\%\{day\}" }



1;

