###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.04).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file cy.xml.
# The source file version number was 1.52, generated on
# 2007/07/19 22:31:38.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::cy;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::cy::ISA = qw(DateTime::Locale::root);

my @day_names = (
"Dydd\ Llun",
"Dydd\ Mawrth",
"Dydd\ Mercher",
"Dydd\ Iau",
"Dydd\ Gwener",
"Dydd\ Sadwrn",
"Dydd\ Sul",
);

my @day_abbreviations = (
"Llun",
"Maw",
"Mer",
"Iau",
"Gwen",
"Sad",
"Sul",
);

my @day_narrows = (
"L",
"M",
"M",
"I",
"G",
"S",
"S",
);

my @month_names = (
"Ionawr",
"Chwefror",
"Mawrth",
"Ebrill",
"Mai",
"Mehefin",
"Gorffenaf",
"Awst",
"Medi",
"Hydref",
"Tachwedd",
"Rhagfyr",
);

my @month_abbreviations = (
"Ion",
"Chwef",
"Mawrth",
"Ebrill",
"Mai",
"Meh",
"Gorff",
"Awst",
"Medi",
"Hyd",
"Tach",
"Rhag",
);

my @month_narrows = (
"I",
"C",
"M",
"E",
"M",
"M",
"G",
"A",
"M",
"H",
"T",
"R",
);

my @quarter_names = (
"Q1",
"Q2",
"Q3",
"Q4",
);

my @quarter_abbreviations = (
"Q1",
"Q2",
"Q3",
"Q4",
);

my @am_pms = (
"AM",
"PM",
);

my @era_abbreviations = (
"BCE",
"CE",
);

my $date_before_time = "1";
my $date_parts_order = "dmy";


sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub day_narrows                    { \@day_narrows }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub month_narrows                  { \@month_narrows }
sub quarter_names                  { \@quarter_names }
sub quarter_abbreviations          { \@quarter_abbreviations }
sub am_pms                         { \@am_pms }
sub era_abbreviations              { \@era_abbreviations }
sub full_date_format               { "\%A\,\ \%d\ \%B\ \%\{ce_year\}" }
sub long_date_format               { "\%d\ \%B\ \%\{ce_year\}" }
sub medium_date_format             { "\%\{day\}\ \%b\ \%\{ce_year\}" }
sub short_date_format              { "\%d\/\%m\/\%\{ce_year\}" }
sub full_time_format               { "\%H\:\%M\:\%S\ v" }
sub long_time_format               { "\%H\:\%M\:\%S\ \%\{time_zone_long_name\}" }
sub medium_time_format             { "\%H\:\%M\:\%S" }
sub short_time_format              { "\%H\:\%M" }
sub date_before_time               { $date_before_time }
sub date_parts_order               { $date_parts_order }



1;

