###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.04).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file ee.xml.
# The source file version number was 1.26, generated on
# 2007/07/19 22:31:38.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::ee;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::ee::ISA = qw(DateTime::Locale::root);

my @day_names = (
"Dzoɖa",
"Braɖa",
"Kuɖa",
"Yawoɖa",
"Fiɖa",
"Memleɖa",
"Kɔsiɖa",
);

my @day_abbreviations = (
"Dzo",
"Bra",
"Kuɖ",
"Yaw",
"Fiɖ",
"Mem",
"Kɔs\ Kwe",
);

my @day_narrows = (
"D",
"B",
"K",
"Y",
"F",
"M",
"K",
);

my @month_names = (
"Dzove",
"Dzodze",
"Tedoxe",
"Afɔfiɛ",
"Dama",
"Masa",
"Siamlɔm",
"Deasiamime",
"Anyɔnyɔ",
"Kele",
"Adeɛmekpɔxe",
"Dzome",
);

my @month_abbreviations = (
"Dzv",
"Dzd",
"Ted",
"Afɔ",
"Dam",
"Mas",
"Sia",
"Dea",
"Any",
"Kel",
"Ade",
"Dzm",
);

my @month_narrows = (
"D",
"D",
"T",
"A",
"D",
"M",
"S",
"D",
"A",
"K",
"A",
"D",
);

my @quarter_names = (
"Q1",
"Q2",
"Q3",
"Q4",
);

my @quarter_abbreviations = (
"Q1",
"Q2",
"Q3",
"Q4",
);

my @am_pms = (
"AN",
"EW",
);

my @era_names = (
"Hafi\ Yesu\ Va\ Do\ ŋgɔ\ na\ Yesu",
"Yesu\ Ŋɔli",
);

my @era_abbreviations = (
"HY",
"YŊ",
);

my $date_before_time = "1";
my $date_parts_order = "ymd";


sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub day_narrows                    { \@day_narrows }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub month_narrows                  { \@month_narrows }
sub quarter_names                  { \@quarter_names }
sub quarter_abbreviations          { \@quarter_abbreviations }
sub am_pms                         { \@am_pms }
sub era_names                      { \@era_names }
sub era_abbreviations              { \@era_abbreviations }
sub full_date_format               { "\%A\,\ \%\{ce_year\}\ \%B\ \%d" }
sub long_date_format               { "\%\{ce_year\}\ \%B\ \%\{day\}" }
sub medium_date_format             { "\%\{ce_year\}\ \%b\ \%\{day\}" }
sub short_date_format              { "\%y\/\%m\/\%d" }
sub full_time_format               { "\%H\:\%M\:\%S\ v" }
sub long_time_format               { "\%H\:\%M\:\%S\ \%\{time_zone_long_name\}" }
sub medium_time_format             { "\%H\:\%M\:\%S" }
sub short_time_format              { "\%H\:\%M" }
sub date_before_time               { $date_before_time }
sub date_parts_order               { $date_parts_order }



1;

