###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.04).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file es_PE.xml.
# The source file version number was 1.51, generated on
# 2007/07/21 21:12:28.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::es_PE;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::es;

@DateTime::Locale::es_PE::ISA = qw(DateTime::Locale::es);

my $date_parts_order = "dmy";


sub short_date_format              { "\%\{day\}\/\%m\/\%y" }
sub full_time_format               { "\%HH\%M\'\%S\"\ v" }
sub date_parts_order               { $date_parts_order }



1;

