###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.04).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file fa.xml.
# The source file version number was 1.78, generated on
# 2007/07/19 23:30:28.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::fa;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::fa::ISA = qw(DateTime::Locale::root);

my @day_names = (
"دوشنبه",
"سه‌شنبه",
"چهارشنبه",
"پنجشنبه",
"جمعه",
"شنبه",
"یکشنبه",
);

my @day_abbreviations = (
"دوشنبه",
"سه‌شنبه",
"چهارشنبه",
"پنجشنبه",
"جمعه",
"شنبه",
"یکشنبه",
);

my @day_narrows = (
"د",
"س",
"چ",
"پ",
"ج",
"ش",
"ی",
);

my @month_names = (
"ژانویهٔ",
"فوریهٔ",
"مارس",
"آوریل",
"مهٔ",
"ژوئن",
"ژوئیهٔ",
"اوت",
"سپتامبر",
"اکتبر",
"نوامبر",
"دسامبر",
);

my @month_abbreviations = (
"1",
"2",
"3",
"4",
"5",
"6",
"7",
"8",
"9",
"10",
"11",
"12",
);

my @month_narrows = (
"ژ",
"ف",
"م",
"آ",
"م",
"ژ",
"ژ",
"ا",
"س",
"ا",
"ن",
"د",
);

my @quarter_names = (
"سه‌ماههٔ\ اول",
"سه‌ماههٔ\ دوم",
"سه‌ماههٔ\ سوم",
"سه‌ماههٔ\ چهارم",
);

my @quarter_abbreviations = (
"Q1",
"Q2",
"Q3",
"Q4",
);

my @am_pms = (
"قبل\ از\ ظهر",
"بعد\ از\ ظهر",
);

my @era_names = (
"قبل\ از\ میلاد",
"میلادی",
);

my @era_abbreviations = (
"ق\.م\.",
"م\.",
);

my $default_date_format_length = "long";
my $date_parts_order = "ymd";


sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub day_narrows                    { \@day_narrows }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub month_narrows                  { \@month_narrows }
sub quarter_names                  { \@quarter_names }
sub quarter_abbreviations          { \@quarter_abbreviations }
sub am_pms                         { \@am_pms }
sub era_names                      { \@era_names }
sub era_abbreviations              { \@era_abbreviations }
sub full_date_format               { "\%A\ \%\{day\}\ \%B\ \%\{ce_year\}\ \%\{era\}" }
sub long_date_format               { "\%\{day\}\ \%B\ \%\{ce_year\}" }
sub medium_date_format             { "\%\{ce_year\}\/\%\{month\}\/\%\{day\}" }
sub short_date_format              { "\%y\/\%\{month\}\/\%\{day\}" }
sub full_time_format               { "\%\{hour\}\:\%M\:\%S\ \(vvvv\)" }
sub long_time_format               { "\%\{hour\}\:\%M\:\%S\ \(\%\{time_zone_long_name\}\)" }
sub medium_time_format             { "\%\{hour\}\:\%M\:\%S" }
sub short_time_format              { "\%\{hour\}\:\%M" }
sub _default_date_format_length    { $default_date_format_length }
sub date_parts_order               { $date_parts_order }



1;

