###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.04).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file fa_AF.xml.
# The source file version number was 1.55, generated on
# 2007/07/19 22:31:39.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::fa_AF;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::fa;

@DateTime::Locale::fa_AF::ISA = qw(DateTime::Locale::fa);

my @month_names = (
"جنوری",
"فبروری",
"مارچ",
"اپریل",
"می",
"جون",
"جولای",
"اگست",
"سپتمبر",
"اکتوبر",
"نومبر",
"دسمبر",
);

my @month_narrows = (
"ج",
"ف",
"م",
"ا",
"م",
"ج",
"ج",
"ا",
"س",
"ا",
"ن",
"د",
);



sub month_names                    { \@month_names }
sub month_narrows                  { \@month_narrows }



1;

