###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.04).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file fil.xml.
# The source file version number was 1.7, generated on
# 2007/07/19 23:30:28.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::fil;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::fil::ISA = qw(DateTime::Locale::root);

my @day_names = (
"Lunes",
"Martes",
"Miyerkules",
"Huwebes",
"Biyernes",
"Sabado",
"Linggo",
);

my @day_abbreviations = (
"LU",
"MA",
"MI",
"HU",
"BI",
"SA",
"LI",
);

my @day_narrows = (
"L",
"M",
"M",
"H",
"B",
"S",
"L",
);

my @month_names = (
"Enero",
"Pebrero",
"Marso",
"Abril",
"Mayo",
"Hunyo",
"Hulyo",
"Agosto",
"Septiyembre",
"Oktubre",
"Nobyembre",
"Disyembre",
);

my @month_abbreviations = (
"Ene",
"Peb",
"Mar",
"Apr",
"May",
"Hun",
"Hul",
"Ago",
"Set",
"Okt",
"Nob",
"Dis",
);

my @month_narrows = (
"E",
"P",
"M",
"A",
"M",
"H",
"H",
"A",
"S",
"O",
"N",
"D",
);

my $date_parts_order = "mdy";


sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub day_narrows                    { \@day_narrows }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub month_narrows                  { \@month_narrows }
sub full_date_format               { "\%A\,\ \%B\ \%d\ \%\{ce_year\}" }
sub long_date_format               { "\%B\ \%\{day\}\,\ \%\{ce_year\}" }
sub medium_date_format             { "\%b\ \%\{day\}\,\ \%\{ce_year\}" }
sub short_date_format              { "\%\{month\}\/\%\{day\}\/\%y" }
sub date_parts_order               { $date_parts_order }



1;

