###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.04).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file hy.xml.
# The source file version number was 1.59, generated on
# 2007/07/19 23:30:28.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::hy;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::hy::ISA = qw(DateTime::Locale::root);

my @day_names = (
"Երկուշաբթի",
"Երեքշաբթի",
"Չորեքշաբթի",
"Հինգշաբթի",
"Ուրբաթ",
"Շաբաթ",
"Կիրակի",
);

my @day_abbreviations = (
"Երկ",
"Երք",
"Չոր",
"Հնգ",
"Ուր",
"Շաբ",
"Կիր",
);

my @day_narrows = (
"2",
"3",
"4",
"5",
"6",
"7",
"1",
);

my @month_names = (
"Յունուար",
"Փետրուար",
"Մարտ",
"Ապրիլ",
"Մայիս",
"Յունիս",
"Յուլիս",
"Օգոստոս",
"Սեպտեմբեր",
"Հոկտեմբեր",
"Նոյեմբեր",
"Դեկտեմբեր",
);

my @month_abbreviations = (
"Յնր",
"Փտր",
"Մրտ",
"Ապր",
"Մյս",
"Յնս",
"Յլս",
"Օգս",
"Սեպ",
"Հոկ",
"Նոյ",
"Դեկ",
);

my @month_narrows = (
"1",
"2",
"3",
"4",
"5",
"6",
"7",
"8",
"9",
"10",
"11",
"12",
);

my @quarter_names = (
"Q1",
"Q2",
"Q3",
"Q4",
);

my @quarter_abbreviations = (
"Q1",
"Q2",
"Q3",
"Q4",
);

my @am_pms = (
"Առ․",
"Եր․",
);

my @era_abbreviations = (
"Յ․Տ․",
"Ն․Ք․",
);

my $date_before_time = "1";
my $date_parts_order = "mdy";


sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub day_narrows                    { \@day_narrows }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub month_narrows                  { \@month_narrows }
sub quarter_names                  { \@quarter_names }
sub quarter_abbreviations          { \@quarter_abbreviations }
sub am_pms                         { \@am_pms }
sub era_abbreviations              { \@era_abbreviations }
sub full_date_format               { "\%A\,\ \%B\ \%\{day\}\,\ \%\{ce_year\}" }
sub long_date_format               { "\%B\ \%d\,\ \%\{ce_year\}" }
sub medium_date_format             { "\%b\ \%\{day\}\,\ \%\{ce_year\}" }
sub short_date_format              { "\%m\/\%d\/\%y" }
sub full_time_format               { "\%H\:\%M\:\%S\ v" }
sub long_time_format               { "\%H\:\%M\:\%S\ \%\{time_zone_long_name\}" }
sub medium_time_format             { "\%H\:\%M\:\%S" }
sub short_time_format              { "\%H\:\%M" }
sub date_before_time               { $date_before_time }
sub date_parts_order               { $date_parts_order }



1;

