###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.04).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file ii.xml.
# The source file version number was 1.4, generated on
# 2007/07/19 22:31:39.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::ii;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::ii::ISA = qw(DateTime::Locale::root);

my @day_names = (
"ꆏꊂꋍ",
"ꆏꊂꑍ",
"ꆏꊂꌕ",
"ꆏꊂꇖ",
"ꆏꊂꉬ",
"ꆏꊂꃘ",
"ꑭꆏꑍ",
);

my @day_abbreviations = (
"ꆏꋍ",
"ꆏꑍ",
"ꆏꌕ",
"ꆏꇖ",
"ꆏꉬ",
"ꆏꃘ",
"ꆏꑍ",
);

my @day_narrows = (
"ꋍ",
"ꑍ",
"ꌕ",
"ꇖ",
"ꉬ",
"ꃘ",
"ꆏ",
);

my @month_names = (
"ꋍꆪ",
"ꑍꆪ",
"ꌕꆪ",
"ꇖꆪ",
"ꉬꆪ",
"ꃘꆪ",
"ꏃꆪ",
"ꉆꆪ",
"ꈬꆪ",
"ꊰꆪ",
"ꊰꊪꆪ",
"ꊰꑋꆪ",
);

my @month_abbreviations = (
"1",
"2",
"3",
"4",
"5",
"6",
"7",
"8",
"9",
"10",
"11",
"12",
);

my @month_narrows = (
"1",
"2",
"3",
"4",
"5",
"6",
"7",
"8",
"9",
"10",
"11",
"12",
);

my @quarter_names = (
"ꃅꑌ",
"ꃅꎸ",
"ꃅꍵ",
"ꃅꋆ",
);

my @quarter_abbreviations = (
"ꃅꑌ",
"ꃅꎸ",
"ꃅꍵ",
"ꃅꋆ",
);

my @am_pms = (
"ꎸꄑ",
"ꁯꋒ",
);

my @era_abbreviations = (
"ꃅꋊꂿ",
"ꃅꋊꊂ",
);



sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub day_narrows                    { \@day_narrows }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub month_narrows                  { \@month_narrows }
sub quarter_names                  { \@quarter_names }
sub quarter_abbreviations          { \@quarter_abbreviations }
sub am_pms                         { \@am_pms }
sub era_abbreviations              { \@era_abbreviations }
sub long_date_format               { "\%\{ce_year\}\ \%B\ \%\{day\}" }



1;

