###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.04).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file it.xml.
# The source file version number was 1.92, generated on
# 2007/07/20 17:14:05.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::it;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::it::ISA = qw(DateTime::Locale::root);

my @day_names = (
"lunedì",
"martedì",
"mercoledì",
"giovedì",
"venerdì",
"sabato",
"domenica",
);

my @day_abbreviations = (
"lun",
"mar",
"mer",
"gio",
"ven",
"sab",
"dom",
);

my @day_narrows = (
"L",
"M",
"M",
"G",
"V",
"S",
"D",
);

my @month_names = (
"gennaio",
"febbraio",
"marzo",
"aprile",
"maggio",
"giugno",
"luglio",
"agosto",
"settembre",
"ottobre",
"novembre",
"dicembre",
);

my @month_abbreviations = (
"gen",
"feb",
"mar",
"apr",
"mag",
"giu",
"lug",
"ago",
"set",
"ott",
"nov",
"dic",
);

my @month_narrows = (
"G",
"F",
"M",
"A",
"M",
"G",
"L",
"A",
"S",
"O",
"N",
"D",
);

my @quarter_names = (
"1o\ trimestre",
"2o\ trimestre",
"3o\ trimestre",
"4o\ trimestre",
);

my @quarter_abbreviations = (
"T1",
"T2",
"T3",
"T4",
);

my @am_pms = (
"m\.",
"p\.",
);

my @era_names = (
"a\.C\.",
"d\.C\.",
);

my @era_abbreviations = (
"aC",
"dC",
);

my $date_before_time = "1";
my $date_parts_order = "dmy";


sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub day_narrows                    { \@day_narrows }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub month_narrows                  { \@month_narrows }
sub quarter_names                  { \@quarter_names }
sub quarter_abbreviations          { \@quarter_abbreviations }
sub am_pms                         { \@am_pms }
sub era_names                      { \@era_names }
sub era_abbreviations              { \@era_abbreviations }
sub full_date_format               { "\%A\ \%\{day\}\ \%B\ \%\{ce_year\}" }
sub long_date_format               { "\%d\ \%B\ \%\{ce_year\}" }
sub medium_date_format             { "\%d\/\%b\/\%\{ce_year\}" }
sub short_date_format              { "\%d\/\%m\/\%y" }
sub full_time_format               { "\%H\:\%M\:\%S\ v" }
sub long_time_format               { "\%H\:\%M\:\%S\ \%\{time_zone_long_name\}" }
sub medium_time_format             { "\%H\:\%M\:\%S" }
sub short_time_format              { "\%H\:\%M" }
sub date_before_time               { $date_before_time }
sub date_parts_order               { $date_parts_order }



1;

