###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.04).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file ja.xml.
# The source file version number was 1.114, generated on
# 2007/07/24 23:39:15.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::ja;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::ja::ISA = qw(DateTime::Locale::root);

my @day_names = (
"月曜日",
"火曜日",
"水曜日",
"木曜日",
"金曜日",
"土曜日",
"日曜日",
);

my @day_abbreviations = (
"月",
"火",
"水",
"木",
"金",
"土",
"日",
);

my @day_narrows = (
"月",
"火",
"水",
"木",
"金",
"土",
"日",
);

my @month_names = (
"1\ 月",
"2\ 月",
"3\ 月",
"4\ 月",
"5\ 月",
"6\ 月",
"7\ 月",
"8\ 月",
"9\ 月",
"10\ 月",
"11\ 月",
"12\ 月",
);

my @month_abbreviations = (
"1\ 月",
"2\ 月",
"3\ 月",
"4\ 月",
"5\ 月",
"6\ 月",
"7\ 月",
"8\ 月",
"9\ 月",
"10\ 月",
"11\ 月",
"12\ 月",
);

my @month_narrows = (
"1",
"2",
"3",
"4",
"5",
"6",
"7",
"8",
"9",
"10",
"11",
"12",
);

my @quarter_names = (
"第\ 1\ 四半期",
"第\ 2\ 四半期",
"第\ 3\ 四半期",
"第\ 4\ 四半期",
);

my @quarter_abbreviations = (
"Q1",
"Q2",
"Q3",
"Q4",
);

my @am_pms = (
"午前",
"午後",
);

my @era_names = (
"紀元前",
"西暦",
);

my @era_abbreviations = (
"紀元前",
"西暦",
);

my $date_before_time = "1";
my $date_parts_order = "ymd";


sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub day_narrows                    { \@day_narrows }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub month_narrows                  { \@month_narrows }
sub quarter_names                  { \@quarter_names }
sub quarter_abbreviations          { \@quarter_abbreviations }
sub am_pms                         { \@am_pms }
sub era_names                      { \@era_names }
sub era_abbreviations              { \@era_abbreviations }
sub full_date_format               { "\%\{ce_year\}年\%\{month\}月\%\{day\}日\%A" }
sub long_date_format               { "\%\{ce_year\}年\%\{month\}月\%\{day\}日" }
sub medium_date_format             { "\%\{ce_year\}\/\%m\/\%d" }
sub short_date_format              { "\%y\/\%m\/\%d" }
sub full_time_format               { "\%\{hour\}時\%M分\%S秒v" }
sub long_time_format               { "\%\{hour\}\:\%M\:\%S\:\%\{time_zone_long_name\}" }
sub medium_time_format             { "\%\{hour\}\:\%M\:\%S" }
sub short_time_format              { "\%\{hour\}\:\%M" }
sub date_before_time               { $date_before_time }
sub date_parts_order               { $date_parts_order }



1;

