###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.04).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file lt.xml.
# The source file version number was 1.86, generated on
# 2007/07/19 22:31:39.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::lt;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::lt::ISA = qw(DateTime::Locale::root);

my @day_names = (
"pirmadienis",
"antradienis",
"trečiadienis",
"ketvirtadienis",
"penktadienis",
"šeštadienis",
"sekmadienis",
);

my @day_abbreviations = (
"Pirmadienis",
"Antradienis",
"Treč\.",
"Ketvirtadienis",
"Penk\.",
"Šeštadienis",
"Skm\.",
);

my @day_narrows = (
"P",
"A",
"T",
"K",
"P",
"Š",
"S",
);

my @month_names = (
"sausis",
"vasaris",
"kovas",
"balandis",
"gegužė",
"birželis",
"liepa",
"rugpjūtis",
"rugsėjis",
"spalis",
"lapkritis",
"gruodis",
);

my @month_abbreviations = (
"Sau",
"Vas",
"Kov",
"Bal",
"Geg",
"Bir",
"Lie",
"Rgp",
"Rgs",
"Spl",
"Lap",
"Grd",
);

my @month_narrows = (
"S",
"V",
"K",
"B",
"G",
"B",
"L",
"R",
"R",
"S",
"L",
"G",
);

my @quarter_names = (
"pirmas\ ketvirtis",
"antras\ ketvirtis",
"trečias\ ketvirtis",
"ketvirtas\ ketvirtis",
);

my @quarter_abbreviations = (
"K1",
"K2",
"K3",
"K4",
);

my @am_pms = (
"priešpiet",
"popiet",
);

my @era_abbreviations = (
"pr\.\ Kr\.",
"po\ Kr\.",
);

my $date_before_time = "1";
my $date_parts_order = "ymd";


sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub day_narrows                    { \@day_narrows }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub month_narrows                  { \@month_narrows }
sub quarter_names                  { \@quarter_names }
sub quarter_abbreviations          { \@quarter_abbreviations }
sub am_pms                         { \@am_pms }
sub era_abbreviations              { \@era_abbreviations }
sub full_date_format               { "\%\{ce_year\}\ m\.\ \%B\ \%\{day\}\ d\.\,\%A" }
sub long_date_format               { "\%\{ce_year\}\ m\.\ \%B\ \%\{day\}\ d\." }
sub medium_date_format             { "\%\{ce_year\}\.\%m\.\%d" }
sub short_date_format              { "\%\{ce_year\}\-\%m\-\%d" }
sub full_time_format               { "\%H\:\%M\:\%S\ v" }
sub long_time_format               { "\%H\:\%M\:\%S\ \%\{time_zone_long_name\}" }
sub medium_time_format             { "\%H\:\%M\:\%S" }
sub short_time_format              { "\%H\:\%M" }
sub date_before_time               { $date_before_time }
sub date_parts_order               { $date_parts_order }



1;

