###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.04).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file lv.xml.
# The source file version number was 1.70, generated on
# 2007/07/19 23:40:49.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::lv;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::lv::ISA = qw(DateTime::Locale::root);

my @day_names = (
"pirmdiena",
"otrdiena",
"trešdiena",
"ceturtdiena",
"piektdiena",
"sestdiena",
"svētdiena",
);

my @day_abbreviations = (
"Pirmdiena",
"Ot",
"Trešd",
"Ce",
"Piektd",
"Se",
"Saule",
);

my @day_narrows = (
"2",
"3",
"4",
"5",
"6",
"7",
"1",
);

my @month_names = (
"janvāris",
"februāris",
"marts",
"aprīlis",
"maijs",
"jūnijs",
"jūlijs",
"augusts",
"septembris",
"oktobris",
"novembris",
"decembris",
);

my @month_abbreviations = (
"Jan",
"Feb",
"Mar",
"Apr",
"Mai",
"Jūn",
"Jūl",
"Aug",
"Sep",
"Okt",
"Nov",
"Dec",
);

my @month_narrows = (
"1",
"2",
"3",
"4",
"5",
"6",
"7",
"8",
"9",
"10",
"11",
"12",
);

my @quarter_names = (
"1\.\ ceturksnis",
"2\.\ ceturksnis",
"3\.\ ceturksnis",
"4\.\ ceturksnis",
);

my @quarter_abbreviations = (
"C1",
"C2",
"C3",
"C4",
);

my @am_pms = (
"AM",
"PM",
);

my @era_names = (
"pirms\ mūsu\ ēras",
"mūsu\ ērā",
);

my @era_abbreviations = (
"p\.m\.ē\.",
"m\.ē\.",
);

my $date_before_time = "1";
my $date_parts_order = "ydm";


sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub day_narrows                    { \@day_narrows }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub month_narrows                  { \@month_narrows }
sub quarter_names                  { \@quarter_names }
sub quarter_abbreviations          { \@quarter_abbreviations }
sub am_pms                         { \@am_pms }
sub era_names                      { \@era_names }
sub era_abbreviations              { \@era_abbreviations }
sub full_date_format               { "\%A\,\ \%\{ce_year\}\.\ gada\ \%\{day\}\.\ \%B" }
sub long_date_format               { "\%\{ce_year\}\.\ gada\ \%\{day\}\.\ \%B" }
sub medium_date_format             { "\%\{ce_year\}\.\%\{day\}\.\%\{month\}" }
sub short_date_format              { "\%y\.\%\{day\}\.\%\{month\}" }
sub full_time_format               { "\%H\:\%M\:\%S\ v" }
sub long_time_format               { "\%H\:\%M\:\%S\ \%\{time_zone_long_name\}" }
sub medium_time_format             { "\%H\:\%M\:\%S" }
sub short_time_format              { "\%H\:\%M" }
sub date_before_time               { $date_before_time }
sub date_parts_order               { $date_parts_order }



1;

