###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.04).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file ml.xml.
# The source file version number was 1.42, generated on
# 2007/07/26 04:28:12.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::ml;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::ml::ISA = qw(DateTime::Locale::root);

my @day_names = (
"തിങ്കള്അ",
"ചൊവ്വ",
"ബുനഭ്അ",
"വ്യാഴം",
"വെള്ളി",
"ശനി",
"ഞായറ്അ",
);

my @day_abbreviations = (
"തി",
"ചൊ",
"ബു",
"വ്യ",
"വെ",
"ശ",
"ഞാ",
);

my @day_narrows = (
"2",
"3",
"4",
"5",
"6",
"7",
"1",
);

my @month_names = (
"ജനുവരി",
"ഫിബ്റവരി",
"മാറ്അച്അച്",
"ഏപ്റില്അ",
"മെയ്",
"ജൂണ്അ",
"ജൂൈല",
"ആഗസ്ത്അ",
"സെപ്തംബറ്അ",
"ഒക്ടൈബറ്അ",
"നവംബറ്അ",
"ഡിസംബറ്അ",
);

my @month_abbreviations = (
"ജനു",
"ഫിബ്",
"മാറ്അ",
"ഏപ്റില്അ",
"മെയ്",
"ജൂണ്അ",
"ജൂൈല",
"ആഗ",
"സെപ്തം",
"ഒക്ട",
"നവം",
"ഡിസം",
);

my @quarter_names = (
"Q1",
"Q2",
"Q3",
"Q4",
);

my @quarter_abbreviations = (
"Q1",
"Q2",
"Q3",
"Q4",
);

my @am_pms = (
"രാവിലെ",
"വൈകുന്നേരം",
);

my @era_names = (
"BCE",
"CE",
);

my @era_abbreviations = (
"BCE",
"CE",
);

my $date_before_time = "1";
my $date_parts_order = "dmy";


sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub day_narrows                    { \@day_narrows }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub quarter_names                  { \@quarter_names }
sub quarter_abbreviations          { \@quarter_abbreviations }
sub am_pms                         { \@am_pms }
sub era_names                      { \@era_names }
sub era_abbreviations              { \@era_abbreviations }
sub full_date_format               { "\%\{ce_year\}\,\ \%B\ \%\{day\}\,\ \%A" }
sub long_date_format               { "\%\{ce_year\}\,\ \%B\ \%\{day\}" }
sub medium_date_format             { "\%\{ce_year\}\,\ \%b\ \%\{day\}" }
sub short_date_format              { "\%d\-\%m\-\%y" }
sub full_time_format               { "\%\{hour_12\}\:\%M\:\%S\ \%p\ v" }
sub long_time_format               { "\%\{hour_12\}\:\%M\:\%S\ \%p\ \%\{time_zone_long_name\}" }
sub medium_time_format             { "\%\{hour_12\}\:\%M\:\%S\ \%p" }
sub short_time_format              { "\%\{hour_12\}\:\%M\ \%p" }
sub date_before_time               { $date_before_time }
sub date_parts_order               { $date_parts_order }



1;

