###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.04).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file ro.xml.
# The source file version number was 1.85, generated on
# 2007/07/25 23:11:40.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::ro;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::ro::ISA = qw(DateTime::Locale::root);

my @day_names = (
"luni",
"marţi",
"miercuri",
"joi",
"vineri",
"sîmbătă",
"duminică",
);

my @day_abbreviations = (
"Lu",
"Ma",
"Mi",
"Jo",
"Vi",
"Sb",
"Du",
);

my @day_narrows = (
"Lu",
"Ma",
"Mi",
"Jo",
"Vi",
"Sb",
"Du",
);

my @month_names = (
"ianuarie",
"februarie",
"martie",
"aprilie",
"mai",
"iunie",
"iulie",
"august",
"septembrie",
"octombrie",
"noiembrie",
"decembrie",
);

my @month_abbreviations = (
"Ian",
"Feb",
"Mar",
"Apr",
"Mai",
"Iun",
"Iul",
"Aug",
"Sep",
"Oct",
"Noi",
"Dec",
);

my @month_narrows = (
"I",
"F",
"M",
"A",
"M",
"I",
"I",
"A",
"S",
"O",
"N",
"D",
);

my @quarter_names = (
"trimestrul\ I",
"trimestrul\ al\ II\-lea",
"trimestrul\ al\ III\-lea",
"trimestrul\ al\ IV\-lea",
);

my @quarter_abbreviations = (
"T1",
"T2",
"T3",
"T4",
);

my @am_pms = (
"AM",
"PM",
);

my @era_names = (
"î\.e\.n\.",
"CE",
);

my @era_abbreviations = (
"d\.C\.",
"î\.d\.C\.",
);

my $date_before_time = "1";
my $date_parts_order = "dmy";


sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub day_narrows                    { \@day_narrows }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub month_narrows                  { \@month_narrows }
sub quarter_names                  { \@quarter_names }
sub quarter_abbreviations          { \@quarter_abbreviations }
sub am_pms                         { \@am_pms }
sub era_names                      { \@era_names }
sub era_abbreviations              { \@era_abbreviations }
sub full_date_format               { "\%\{day\}\ \%B\ \%\{ce_year\}" }
sub long_date_format               { "\%\{day\}\ \%B\ \%\{ce_year\}" }
sub medium_date_format             { "\%d\.\%m\.\%\{ce_year\}" }
sub short_date_format              { "\%d\.\%m\.\%\{ce_year\}" }
sub full_time_format               { "\%H\:\%M\:\%S\ v" }
sub long_time_format               { "\%H\:\%M\:\%S\ \%\{time_zone_long_name\}" }
sub medium_time_format             { "\%H\:\%M\:\%S" }
sub short_time_format              { "\%H\:\%M" }
sub date_before_time               { $date_before_time }
sub date_parts_order               { $date_parts_order }



1;

