###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.04).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file ru.xml.
# The source file version number was 1.110, generated on
# 2007/07/20 04:40:45.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::ru;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::ru::ISA = qw(DateTime::Locale::root);

my @day_names = (
"понедельник",
"вторник",
"среда",
"четверг",
"пятница",
"суббота",
"воскресенье",
);

my @day_abbreviations = (
"Пн",
"Вт",
"Ср",
"Чт",
"Пт",
"Сб",
"Вс",
);

my @day_narrows = (
"П",
"В",
"С",
"Ч",
"П",
"С",
"В",
);

my @month_names = (
"январь",
"февраль",
"март",
"апрель",
"май",
"июнь",
"июль",
"август",
"сентябрь",
"октябрь",
"ноябрь",
"декабрь",
);

my @month_abbreviations = (
"янв\.",
"фев\.",
"март",
"апр\.",
"мая",
"июнь",
"июл\.",
"авг\.",
"сент\.",
"окт\.",
"нояб\.",
"дек\.",
);

my @month_narrows = (
"Я",
"Ф",
"М",
"А",
"М",
"И",
"И",
"А",
"С",
"О",
"Н",
"Д",
);

my @quarter_names = (
"1\-й\ квартал",
"2\-й\ квартал",
"3\-й\ квартал",
"4\-й\ квартал",
);

my @quarter_abbreviations = (
"1\-й\ кв\.",
"2\-й\ кв\.",
"3\-й\ кв\.",
"4\-й\ кв\.",
);

my @am_pms = (
"AM",
"PM",
);

my @era_names = (
"до\ Р\.Х\.",
"CE",
);

my @era_abbreviations = (
"до\ н\.э\.",
"н\.э\.",
);

my $date_before_time = "1";
my $date_parts_order = "dmy";


sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub day_narrows                    { \@day_narrows }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub month_narrows                  { \@month_narrows }
sub quarter_names                  { \@quarter_names }
sub quarter_abbreviations          { \@quarter_abbreviations }
sub am_pms                         { \@am_pms }
sub era_names                      { \@era_names }
sub era_abbreviations              { \@era_abbreviations }
sub full_date_format               { "\%\{day\}\ \%B\ \%\{ce_year\}\ г\." }
sub long_date_format               { "\%\{day\}\ \%B\ \%\{ce_year\}\ г\." }
sub medium_date_format             { "\%d\.\%m\.\%\{ce_year\}" }
sub short_date_format              { "\%d\.\%m\.\%y" }
sub full_time_format               { "\%\{hour\}\:\%M\:\%S\ v" }
sub long_time_format               { "\%\{hour\}\:\%M\:\%S\ \%\{time_zone_long_name\}" }
sub medium_time_format             { "\%\{hour\}\:\%M\:\%S" }
sub short_time_format              { "\%\{hour\}\:\%M" }
sub date_before_time               { $date_before_time }
sub date_parts_order               { $date_parts_order }



1;

