###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.04).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file se_FI.xml.
# The source file version number was 1.19, generated on
# 2007/07/19 22:31:40.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::se_FI;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::se;

@DateTime::Locale::se_FI::ISA = qw(DateTime::Locale::se);

my @day_names = (
"måanta",
"däjsta",
"gaskevahkoe",
"dåarsta",
"bearjadahke",
"laavadahke",
"aejlege",
);

my @day_abbreviations = (
"2",
"3",
"4",
"5",
"6",
"7",
"1",
);

my @day_narrows = (
"M",
"D",
"G",
"D",
"B",
"L",
"S",
);

my @month_abbreviations = (
"ođđajage",
"guovva",
"njukča",
"cuoŋo",
"miesse",
"geasse",
"suoidne",
"borge",
"čakča",
"golggot",
"skábma",
"juovla",
);



sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub day_narrows                    { \@day_narrows }
sub month_abbreviations            { \@month_abbreviations }



1;

