###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.04).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file sr_Cyrl_BA.xml.
# The source file version number was 1.29, generated on
# 2007/07/24 23:39:15.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::sr_Cyrl_BA;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::sr;

@DateTime::Locale::sr_Cyrl_BA::ISA = qw(DateTime::Locale::sr);

my $date_parts_order = "ymd";


sub medium_date_format             { "\%\{ce_year\}\-\%m\-\%d" }
sub short_date_format              { "\%y\-\%m\-\%d" }
sub full_time_format               { "\%H\ часова\,\ \%M\ минута\,\ \%S\ секунди\ v" }
sub medium_time_format             { "\%H\:\%M\:\%S" }
sub short_time_format              { "\%H\:\%M" }
sub date_parts_order               { $date_parts_order }



1;

