###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.04).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file sr_Latn_ME.xml.
# The source file version number was 1.12, generated on
# 2007/07/21 21:12:28.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::sr_Latn_ME;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::sr_Latn;

@DateTime::Locale::sr_Latn_ME::ISA = qw(DateTime::Locale::sr_Latn);



sub long_date_format               { "\%\{day\}\.\%m\.\%\{ce_year\}\." }
sub full_time_format               { "\%H\.\%M\.\%S\ v" }



1;

