###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.04).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file ti_ER.xml.
# The source file version number was 1.45, generated on
# 2007/07/14 23:02:17.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::ti_ER;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::ti;

@DateTime::Locale::ti_ER::ISA = qw(DateTime::Locale::ti);

my @month_names = (
"ጥሪ",
"ለካቲት",
"መጋቢት",
"ሚያዝያ",
"ግንቦት",
"ሰነ",
"ሓምለ",
"ነሓሰ",
"መስከረም",
"ጥቅምቲ",
"ሕዳር",
"ታሕሳስ",
);

my @month_abbreviations = (
"ጥሪ",
"ለካቲ",
"መጋቢ",
"ሚያዝ",
"ግንቦ",
"ሰነ",
"ሓምለ",
"ነሓሰ",
"መስከ",
"ጥቅም",
"ሕዳር",
"ታሕሳ",
);



sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub full_date_format               { "\%A፡\ \%d\ \%B\ መዓልቲ\ \%\{ce_year\}\ \%\{era\}" }



1;

