###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.04).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file to.xml.
# The source file version number was 1.5, generated on
# 2007/07/19 22:31:40.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::to;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::to::ISA = qw(DateTime::Locale::root);

my @day_names = (
"Mōnite",
"Tusite",
"Pulelulu",
"Tuʻapulelulu",
"Falaite",
"Tokonaki",
"Sāpate",
);

my @day_abbreviations = (
"Mōn",
"Tus",
"Pul",
"Tuʻa",
"Fal",
"Tok",
"Sāp",
);

my @day_narrows = (
"M",
"T",
"P",
"T",
"F",
"T",
"S",
);

my @month_names = (
"Sānuali",
"Fēpueli",
"Maʻasi",
"ʻEpeleli",
"Mē",
"Sune",
"Siulai",
"ʻAokosi",
"Sēpitema",
"ʻOkatopa",
"Nōvema",
"Tisema",
);

my @month_abbreviations = (
"Sān",
"Fēp",
"Maʻa",
"ʻEpe",
"Mē",
"Sun",
"Siu",
"ʻAok",
"Sēp",
"ʻOka",
"Nōv",
"Tis",
);

my @month_narrows = (
"S",
"F",
"M",
"ʻE",
"M",
"S",
"S",
"ʻA",
"S",
"ʻO",
"N",
"T",
);

my @quarter_names = (
"kuata\ ʻuluaki",
"kuata\ ua",
"kuata\ tolu",
"kuata\ fā",
);

my @quarter_abbreviations = (
"K1",
"K2",
"K3",
"K4",
);

my @am_pms = (
"HH",
"EA",
);

my @era_names = (
"ki\ muʻa",
"taʻu\ ʻo\ Sīsū",
);

my @era_abbreviations = (
"KM",
"TS",
);

my $date_parts_order = "dmy";


sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub day_narrows                    { \@day_narrows }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub month_narrows                  { \@month_narrows }
sub quarter_names                  { \@quarter_names }
sub quarter_abbreviations          { \@quarter_abbreviations }
sub am_pms                         { \@am_pms }
sub era_names                      { \@era_names }
sub era_abbreviations              { \@era_abbreviations }
sub full_date_format               { "\%A\ \%\{day\}\ \%B\ \%\{ce_year\}" }
sub long_date_format               { "\%\{day\}\ \%B\ \%\{ce_year\}" }
sub medium_date_format             { "\%\{day\}\ \%b\ \%\{ce_year\}" }
sub short_date_format              { "\%d\-\%m\-\%\{ce_year\}" }
sub date_parts_order               { $date_parts_order }



1;

