###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.04).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file ve.xml.
# The source file version number was 1.18, generated on
# 2007/07/14 23:02:17.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::ve;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::ve::ISA = qw(DateTime::Locale::root);

my @day_names = (
"Musumbuluwo",
"Ḽavhuvhili",
"Ḽavhuraru",
"Ḽavhuṋa",
"Ḽavhuṱanu",
"Mugivhela",
"Swondaha",
);

my @day_abbreviations = (
"Mus",
"Vhi",
"Rar",
"Ṋa",
"Ṱan",
"Mug",
"Swo",
);

my @day_narrows = (
"2",
"3",
"4",
"5",
"6",
"7",
"1",
);

my @month_names = (
"Phando",
"Luhuhi",
"Ṱhafamuhwe",
"Lambamai",
"Shundunthule",
"Fulwi",
"Fulwana",
"Ṱhangule",
"Khubvumedzi",
"Tshimedzi",
"Ḽara",
"Nyendavhusiku",
);

my @month_abbreviations = (
"Pha",
"Luh",
"Thf",
"Lam",
"Shu",
"Lwi",
"Lwa",
"Ṱha",
"Khu",
"Tsh",
"Ḽar",
"Nye",
);

my @month_narrows = (
"1",
"2",
"3",
"4",
"5",
"6",
"7",
"8",
"9",
"10",
"11",
"12",
);

my @quarter_names = (
"Kotara\ ya\ u\ thoma",
"Kotara\ ya\ vhuvhili",
"Kotara\ ya\ vhuraru",
"Kotara\ ya\ vhuṋa",
);

my @quarter_abbreviations = (
"K1",
"K2",
"K3",
"K4",
);

my @am_pms = (
"AM",
"PM",
);

my @era_names = (
"BC",
"AD",
);

my @era_abbreviations = (
"BC",
"AD",
);

my $date_before_time = "1";
my $date_parts_order = "ymd";


sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub day_narrows                    { \@day_narrows }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub month_narrows                  { \@month_narrows }
sub quarter_names                  { \@quarter_names }
sub quarter_abbreviations          { \@quarter_abbreviations }
sub am_pms                         { \@am_pms }
sub era_names                      { \@era_names }
sub era_abbreviations              { \@era_abbreviations }
sub full_date_format               { "\%A\,\ \%\{ce_year\}\ \%B\ \%d" }
sub long_date_format               { "\%\{ce_year\}\ \%B\ \%\{day\}" }
sub medium_date_format             { "\%\{ce_year\}\ \%b\ \%\{day\}" }
sub short_date_format              { "\%y\/\%m\/\%d" }
sub full_time_format               { "\%H\:\%M\:\%S\ v" }
sub long_time_format               { "\%H\:\%M\:\%S\ \%\{time_zone_long_name\}" }
sub medium_time_format             { "\%H\:\%M\:\%S" }
sub short_time_format              { "\%H\:\%M" }
sub date_before_time               { $date_before_time }
sub date_parts_order               { $date_parts_order }



1;

