###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.04).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file vi.xml.
# The source file version number was 1.60, generated on
# 2007/07/19 23:30:29.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::vi;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::vi::ISA = qw(DateTime::Locale::root);

my @day_names = (
"Thứ\ hai",
"Thứ\ ba",
"Thứ\ tư",
"Thứ\ năm",
"Thứ\ sáu",
"Thứ\ bảy",
"Chủ\ Nhật",
);

my @day_abbreviations = (
"Thứ\ Hai",
"Thứ\ 3",
"Thứ\ Tư",
"Thứ\ Năm",
"Thứ\ Sáu",
"Thứ\ Bảy",
"Chủ\ Nhật",
);

my @day_narrows = (
"2",
"3",
"4",
"5",
"6",
"7",
"1",
);

my @month_names = (
"tháng\ một",
"tháng\ hai",
"tháng\ ba",
"tháng\ tư",
"tháng\ năm",
"tháng\ sáu",
"tháng\ bảy",
"tháng\ tám",
"tháng\ chín",
"tháng\ mười",
"tháng\ mười\ một",
"tháng\ mười\ hai",
);

my @month_abbreviations = (
"tháng\ một",
"tháng\ hai",
"tháng\ ba",
"tháng\ tư",
"thg\ 5",
"tháng\ sáu",
"tháng\ bẩy",
"tháng\ tám",
"tháng\ chín",
"tháng\ mười",
"tháng\ mười\ một",
"tháng\ mười\ hai",
);

my @month_narrows = (
"1",
"2",
"3",
"4",
"5",
"6",
"7",
"8",
"9",
"10",
"11",
"12",
);

my @quarter_names = (
"Q1",
"Q2",
"Q3",
"Q4",
);

my @quarter_abbreviations = (
"Q1",
"Q2",
"Q3",
"Q4",
);

my @am_pms = (
"SA",
"CH",
);

my @era_abbreviations = (
"tr\.\ CN",
"sau\ CN",
);

my $date_parts_order = "dmy";


sub day_names                      { \@day_names }
sub day_abbreviations              { \@day_abbreviations }
sub day_narrows                    { \@day_narrows }
sub month_names                    { \@month_names }
sub month_abbreviations            { \@month_abbreviations }
sub month_narrows                  { \@month_narrows }
sub quarter_names                  { \@quarter_names }
sub quarter_abbreviations          { \@quarter_abbreviations }
sub am_pms                         { \@am_pms }
sub era_abbreviations              { \@era_abbreviations }
sub full_date_format               { "\%A\,\ ngày\ \%d\ \%B\ năm\ \%\{ce_year\}" }
sub long_date_format               { "Ngày\ \%d\ tháng\ \%\{month\}\ năm\ \%\{ce_year\}" }
sub medium_date_format             { "\%d\-\%m\-\%\{ce_year\}" }
sub short_date_format              { "\%d\/\%m\/\%\{ce_year\}" }
sub full_time_format               { "\%H\:\%M\:\%S\ v" }
sub long_time_format               { "\%H\:\%M\:\%S\ \%\{time_zone_long_name\}" }
sub medium_time_format             { "\%H\:\%M\:\%S" }
sub short_time_format              { "\%H\:\%M" }
sub date_parts_order               { $date_parts_order }



1;

