###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.04).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file zh_Hant.xml.
# The source file version number was 1.89, generated on
# 2007/07/27 22:13:28.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::zh_Hant;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::zh;

@DateTime::Locale::zh_Hant::ISA = qw(DateTime::Locale::zh);

my @day_abbreviations = (
"週一",
"週二",
"週三",
"週四",
"週五",
"週六",
"週日",
);

my @quarter_names = (
"第1季",
"第2季",
"第3季",
"第4季",
);

my @quarter_abbreviations = (
"1季",
"2季",
"3季",
"4季",
);

my @era_names = (
"西元前",
"西元",
);

my $date_parts_order = "ymd";


sub day_abbreviations              { \@day_abbreviations }
sub quarter_names                  { \@quarter_names }
sub quarter_abbreviations          { \@quarter_abbreviations }
sub era_names                      { \@era_names }
sub medium_date_format             { "\%\{ce_year\}\/\%\{month\}\/\%\{day\}" }
sub short_date_format              { "\%\{ce_year\}\/\%\{month\}\/\%\{day\}" }
sub full_time_format               { "\%p\%l時\%M分\%S秒\ v" }
sub long_time_format               { "\%p\%l時\%M分\%S秒\ \%\{time_zone_long_name\}" }
sub medium_time_format             { "\%p\ \%\{hour_12\}\:\%M\:\%S" }
sub short_time_format              { "\%p\ \%\{hour_12\}\:\%M" }
sub date_parts_order               { $date_parts_order }



1;

