#
# Created by BAD2_demo.pm.PL
#  ** DO NOT EDIT THIS FILE **
#
package PDL::Demos::BAD2_demo;
use PDL;
use PDL::IO::Misc;
use PDL::Graphics::PGPLOT;

use File::Spec;

PDL::Demos::Routines->import();
sub comment($);
sub act($);
sub output;

sub run {


comment q|

    Your version of PDL has been compiled without support for bad
    values, hence this demo cannot do anything.

|;


}

1;

