#
# Created by BAD_demo.pm.PL
#  ** DO NOT EDIT THIS FILE **
#
package PDL::Demos::BAD_demo;
use PDL;

PDL::Demos::Routines->import();
sub comment($);
sub act($);
sub output;

sub run {


comment q|

    Your version of PDL has been compiled without support for bad
    values, hence this demo doesn't do anything.

|;


}

1;

