---
abstract: 'collection of blocks for processing English'
author:
  - 'Treex team <treex@ufal.mff.cuni.cz>'
build_requires:
  English: 0
  File::Find: 0
  File::Slurp: 9999
  File::Temp: 0
  Readonly: 0
  Test::More: 0
  Treex::Core::Document: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Treex-EN
requires:
  File::Slurp: 0
  Lingua::EN::Tagger: 0
  Moose: 0
  Treex::Block::W2A::ParseMSTperl: 0
  Treex::Block::W2A::Tokenize: 0
  Treex::Core::Block: 0
  Treex::Core::Common: 0
  Treex::Core::Log: 0
  Treex::Core::Resource: 0
  Treex::Tool::Segment::RuleBased: 0
  Treex::Tool::Tagger::Featurama: 0
  Treex::Unilang: 0.08170
  perl: 5.010
  utf8: 0
version: 0.08171
