/* This file is automatically generated by Makefile.PL.
   Don't edit this file, since any changes will be lost */

#ifndef IMAGER_IMCONFIG_H
#define IMAGER_IMCONFIG_H

/*
  Logging system
*/

#define IMAGER_LOG 1

/*
  Parsed giflib version
*/

#define IM_GIFMAJOR 0
#define IM_GIFMINOR 0

/*
  Enable experimental EXIF support
*/

#define IMEXIF_ENABLE 1

#endif
