./batch_zhu.pl data/zhu/subset/x01_risk_rule_rate_role_report.train data/zhu/subset/x01_risk_rule_rate_role_report.devtt 10
./batch_zhu.pl data/zhu/subset/x01_risk_rule_rate_role_report.train data/zhu/subset/x01_risk_rule_rate_role_report.devtt 11
./batch_zhu.pl data/zhu/subset/x01_risk_rule_rate_role_report.train data/zhu/subset/x01_risk_rule_rate_role_report.devtt 11
./batch_zhu.pl data/zhu/subset/x01_risk_rule_rate_role_report.train data/zhu/subset/x01_risk_rule_rate_role_report.devtt 12
./batch_zhu.pl data/zhu/subset/x01_risk_rule_rate_role_report.train data/zhu/subset/x01_risk_rule_rate_role_report.devtt 12
./batch_zhu.pl data/zhu/subset/x01_risk_rule_rate_role_report.train data/zhu/subset/x01_risk_rule_rate_role_report.devtt 13
./batch_zhu.pl data/zhu/subset/x01_risk_rule_rate_role_report.train data/zhu/subset/x01_risk_rule_rate_role_report.devtt 13
./batch_zhu.pl data/zhu/subset/x01_risk_rule_rate_role_report.train data/zhu/subset/x01_risk_rule_rate_role_report.devtt 14
./batch_zhu.pl data/zhu/subset/x01_risk_rule_rate_role_report.train data/zhu/subset/x01_risk_rule_rate_role_report.devtt 14
./batch_zhu.pl data/zhu/subset/x01_risk_rule_rate_role_report.train data/zhu/subset/x01_risk_rule_rate_role_report.devtt 15
./batch_zhu.pl data/zhu/subset/x01_risk_rule_rate_role_report.train data/zhu/subset/x01_risk_rule_rate_role_report.devtt 15
